EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# Static
from django.conf.urls.static import static
from django.conf import settings


# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register('products', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customers.urls')),
    path('', include('cart.urls')),
    path('', include('checkout.urls')),
    path('', include('dashboard.urls')),
    path('', include('storereport.urls')),
    path('', include('analysis.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]
# Static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *


app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('buy_now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove_cart/<int:product_id>/', remove_cart, name='remove_cart'),
]

checkout/urls.py
from django.urls import path
from checkout.views import *


app_name = 'checkout'
urlpatterns = [
    path('checkout/', checkout, name='checkout'),
]

customers/urls.py
from django.urls import path
from customers.views import *


app_name = 'customers'
urlpatterns = [
    path('login/', login, name='login'),
    path('login-2/', login_2, name='login_2'),
    path('logout/', logout, name='logout'),
    path('my-account/', my_account, name='my_account'),
]

store/urls.py
from django.urls import path
from store.views import *


app_name = 'store'
urlpatterns = [
    path('', index, name='index'),
    path('index-2/', index_2, name='index_2'),
    path('subcategory/<int:pk>/', product_list, name='product_list'),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('contact/', contact, name='contact'),
    path('search/', search, name='search'),
    path('users/', users, name='users'),
    path('logout/', logout_user, name='logout_user'),
    path('rss/', read_rss, name='read_rss'),
    path('products-service/', products_service, name='products_service'),
    path('product-service/<int:pk>/', product_service, name='product_service'),
]

cart/models.py
from django.db import models

# Create your models here.

checkout/models.py
from django.db import models
from store.models import Product


class Order(models.Model):
    username = models.EmailField(null=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=500, unique=False)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

store/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')

    def __str__(self):
        return self.name


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT)
    name = models.CharField(max_length=250)
    price = models.FloatField(default=0.0)
    price_origin = models.FloatField(null=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')
    content = RichTextUploadingField(blank=True, null=True)
    public_day = models.DateTimeField(default=timezone.now)
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=264)
    message = models.TextField()

    def __str__(self):
        return self.name + ", " + self.subject


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portfolio = models.URLField(blank=True)
    image = models.ImageField(upload_to='store/users/', default='store/users/user_default.png')

    def __str__(self):
        return self.user.username

customers/forms.py
from django import forms
from customers import models


class FormDangKy(forms.ModelForm):
    ho = forms.CharField(max_length=250, label='Họ', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Họ"
    }))
    ten = forms.CharField(max_length=250, label='Tên', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Tên"
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Email"
    }))
    mat_khau = forms.CharField(max_length=100, label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Mật khẩu"
    }))
    xac_nhan_mat_khau = forms.CharField(max_length=100, label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Xác nhận Mật khẩu"
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Điện thoại"
    }))
    dia_chi = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Địa chỉ",
        "rows": 4,
    }))

    class Meta:
        model = models.Customer
        # fields = '__all__'
        fields = ['ho', 'ten', 'email', 'mat_khau', 'dien_thoai', 'dia_chi']


class FormDangKy2(forms.ModelForm):
    ho = forms.CharField(max_length=250, label='Họ', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Họ"
    }))
    ten = forms.CharField(max_length=250, label='Tên', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Tên"
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Email"
    }))
    mat_khau = forms.CharField(max_length=100, label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Mật khẩu"
    }))
    xac_nhan_mat_khau = forms.CharField(max_length=100, label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Xác nhận Mật khẩu"
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Điện thoại"
    }))
    dia_chi = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Địa chỉ",
        "rows": 4,
    }))
    tinh_tp = forms.CharField(label='Tỉnh/TP', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    quan_huyen = forms.CharField(label='Quận/Huyện', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    phuong_xa = forms.CharField(label='Phường/Xã', widget=forms.Select(attrs={
        "class": "form-control",
    }))

    class Meta:
        model = models.Customer
        # fields = '__all__'
        fields = ['ho', 'ten', 'email', 'mat_khau', 'dien_thoai', 'dia_chi']

store/forms.py
from django import forms
from store import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from store.models import UserProfileInfo

phone_validator = RegexValidator(
    r"((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))", "Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx!")


class FormContact(forms.ModelForm):
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={
        'placeholder': 'Họ tên',
        'class': 'form-control'
    }))
    phone_number = forms.CharField(max_length=20, label='Phone', validators=[phone_validator],
                                   widget=forms.TextInput(attrs={
                                       'placeholder': 'Điện thoại',
                                       'class': 'form-control fh5co_contact_text_box',
                                       'pattern': '((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))',
                                       'title': 'Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx'
                                   }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control'
    }))
    subject = forms.CharField(label='Subject', widget=forms.TextInput(attrs={
        'placeholder': 'Tiêu đề',
        'class': 'form-control'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Nội dung',
        'class': 'form-control',
        'rows': '5'
    }))

    class Meta:
        model = models.Contact
        fields = '__all__'


class FormUser(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Username"
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Email"
    }))
    password = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Password"
    }))
    confirm_password = forms.CharField(max_length=100, label='Confirm Password', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Confirm Password"
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class FormUserProfileInfo(forms.ModelForm):
    portfolio = forms.URLField(required=False, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Portfolio"
    }))
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control-file",
    }))

    class Meta:
        model = UserProfileInfo
        exclude = ('user',)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from store.models import Product
from django.views.decorators.http import require_POST
from store.my_module import *


# Create your views here.
def cart_detail(request):
    # Kiểm tra trạng thái đăng nhập của khách hàng
    session_status = check_session(request, 'sessionKhachHang')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionKhachHang')

    # Giỏ hàng
    cart = Cart(request)

    # Xử lý cập nhật khi có mã giảm giá
    coupon_code = ''
    if request.POST.get('btnCoupon'):
        coupon_code = request.POST.get('coupon')
        if coupon_code == 'LNTRI':
            cart_new = {}
            for c in cart:
                product_new = {
                    str(c['product'].pk): {
                        'quantity': c['quantity'],
                        'price': str(c['product'].price),
                        'coupon': '0.9'
                    }
                }
                cart_new.update(product_new)
                c['coupon'] = 0.9
            else:
                request.session['cart'] = cart_new
        else:
            cart_new = {}
            for c in cart:
                product_new = {
                    str(c['product'].pk): {
                        'quantity': c['quantity'],
                        'price': str(c['product'].price),
                        'coupon': '1'
                    }
                }
                cart_new.update(product_new)
                c['coupon'] = 1
            else:
                request.session['cart'] = cart_new

    # Xử lý cập nhật số lượng
    if request.POST.get('btnUpdateCart'):
        cart_new = {}
        for c in cart:
            quantity_new = int(request.POST.get('quantity2' + str(c['product'].pk)))
            if quantity_new != 0:
                product_new = {
                    str(c['product'].pk): {
                        'quantity': quantity_new,
                        'price': str(c['product'].price),
                        'coupon': '1'
                    }
                }
                cart_new.update(product_new)
            else:
                cart.remove(c['product'])
            c['quantity'] = quantity_new
        else:
            request.session['cart'] = cart_new

    return render(request, 'store/cart.html', {
        'cart': cart,
        'session_status': session_status,
        'session_info': session_info,
    })


@require_POST
def buy_now(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('quantity'):
        cart.add(product=product, quantity=int(request.POST.get('quantity')))
    return redirect('cart:cart_detail')


@require_POST
def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

checkout/views.py
from django.shortcuts import render, redirect
from cart.cart import Cart
from store.my_module import *
from checkout.models import Order, OrderItem
# Email
from EStore.settings import EMAIL_HOST_USER
from django.core.mail import send_mail, EmailMessage


# Create your views here.
def checkout(request):
    # Kiểm tra trạng thái đăng nhập của khách hàng
    session_status = check_session(request, 'sessionKhachHang')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionKhachHang')
    else:
        return redirect('cart:cart_detail')

    # Giỏ hàng
    cart = Cart(request)

    # Ghi vào CSDL
    order = Order()
    if request.POST.get('btnOrder'):
        order.username = session_info['email']
        order.first_name = session_info['ten']
        order.last_name = session_info['ho']
        order.phone = session_info['dien_thoai']
        order.address = session_info['dia_chi']
        order.total = cart.get_final_total_price()
        order.save()

        # Chi tiết đơn hàng
        for c in cart:
            OrderItem.objects.create(order=order,
                                     product=c['product'],
                                     price=c['price'],
                                     quantity=c['quantity'])

        # Gửi email
        email_address = order.username
        subject = 'Xác nhận đơn hàng ' + str(order.id)
        message = 'Cảm ơn quý khách <b>' + order.last_name + ' ' + order.first_name + \
                  '</b> đã đặt hàng tại EStore. Danh sách các sản phẩm đã đặt như sau:<br>'

        message += '''
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Tên sản phẩm</th>
                    <th scope="col">Số lượng</th>
                    <th scope="col">Đơn giá</th>
                    <th scope="col">Thành tiền</th>
                </tr>
            </thead>
            <tbody>'''
        for c in cart:
            message += '''<tr>
                <th scope="row">1</th>
                <td>''' + str(c['product']) + '''</td>
                <td>''' + str(c['quantity']) + '''</td>
                <td>''' + str(c['product'].price) + '''</td>
                <td>''' + str(c['total_price']) + '''</td>
            </tr>'''
        message += '''</tbody>
        </table>
        '''

        msg = EmailMessage(subject, message, EMAIL_HOST_USER, [email_address])
        msg.content_subtype = 'html'
        msg.send()

        # Xóa giỏ hàng sau khi đặt hàng thành công
        cart.clear()

        return render(request, 'store/result.html', {
            'cart': cart,
            'session_status': session_status,
            'session_info': session_info,
        })

    return render(request, 'store/checkout.html', {
        'cart': cart,
        'session_status': session_status,
        'session_info': session_info,
    })

store/templates/store/_Master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title_tab %}{% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'store/images/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'store/css/style.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        support@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->
        
        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'store:index' %}" class="nav-item nav-link active">Trang chủ</a>
                            <a href="{% url 'store:product_list' 0 %}" class="nav-item nav-link">Sản phẩm</a>
                            <a href="{% url 'store:read_rss' %}" class="nav-item nav-link">RSS</a>
                            <a href="{% url 'store:contact' %}" class="nav-item nav-link">Liên hệ</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            {% if session_status %}
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ session_info.ho }} {{ session_info.ten }}</a>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'customers:my_account' %}" class="dropdown-item">Thông tin của tôi</a>
                                        <a href="{% url 'customers:logout' %}" class="dropdown-item">Đăng xuất</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'customers:login' %}" class="nav-item nav-link">Đăng nhập</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->      
        
        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'store:index' %}">
                                <img src="{% static 'store/img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="search">
                            <form method="get" action="{% url 'store:search' %}">
                                <input type="text" placeholder="Tìm kiếm sản phẩm..." name="product_name" autocomplete="off" value="{{ product_name }}">
                                <button type="submit"><i class="fa fa-search"></i></button>
                                {% comment %} Bạn đã ghé thăm website này {{ visits }} lần {% endcomment %}
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
{#                            <a href="wishlist.html" class="btn wishlist">#}
{#                                <i class="fa fa-heart"></i>#}
{#                                <span>(0)</span>#}
{#                            </a>#}
                            <a href="{% url 'cart:cart_detail' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{ cart|length }})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->       
        
        {% block content %}{% endblock %}
        
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'store/img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'store/img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'store/img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'store/img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->       
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'store/lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'store/lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'store/js/main.js' %}"></script>
    </body>
</html>

store/templates/store/result.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}
{% block head_title %}EStore | Đặt hàng{% endblock %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Trang chủ</a></li>
                <li class="breadcrumb-item active">Đặt hàng</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Start -->
    <div class="checkout">
        <div class="container-fluid">
            <div class="text-center">
                <img src="{% static 'store/images/success.png' %}" width="20%" />
                <p><h2>Đặt hàng thành công</h2></p>
                <p><h4>Cảm ơn bạn đã đặt hàng. Đơn hàng của bạn sẽ được chuyển đến bạn trong thời gian sớm nhất.</h4></p>
                <br>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

{% endblock %}

store/templates/store/rss.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Trang chủ</a></li>
                <li class="breadcrumb-item active">RSS</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- My Account Start -->
    <div class="my-account">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content">


                        {% for entry in newsfeed.entries %}
                            <div>
                                <h4><a href="{{ entry.link }}" target="_blank">{{ entry.title }}</a></h4>
                                <p>
                                    {{ entry.summary|safe }}
                                </p>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- My Account End -->
{% endblock %}